import type { LucideIcon } from "lucide-react";
import {
  BadgeDollarSign,
  Banknote,
  Briefcase,
  Car,
  Circle,
  Coins,
  Gamepad2,
  Gift,
  GraduationCap,
  HeartPulse,
  House,
  Landmark,
  PiggyBank,
  Plane,
  Receipt,
  ShoppingCart,
  Sparkles,
  Utensils,
  Wallet,
  Wrench,
} from "lucide-react";
import type { CategoryIconName } from "@expense-management/shared";

export const CATEGORY_ICON_COMPONENTS: Record<CategoryIconName, LucideIcon> = {
  Circle,
  Wallet,
  Landmark,
  Banknote,
  Coins,
  BadgeDollarSign,
  Briefcase,
  PiggyBank,
  ShoppingCart,
  Utensils,
  Car,
  House,
  HeartPulse,
  GraduationCap,
  Plane,
  Receipt,
  Gamepad2,
  Gift,
  Wrench,
  Sparkles,
};
